# Generated by Django 2.2.9 on 2020-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdownpage',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='markdownpage',
            name='version',
        ),
        migrations.RemoveField(
            model_name='markdownpagearchive',
            name='version',
        ),
        migrations.AlterField(
            model_name='markdownpage',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PUB', 'Published'), ('GONE', 'Withdrawn')], db_index=True, default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='markdownpagetype',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PUB', 'Published'), ('GONE', 'Withdrawn')], db_index=True, default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='subtype',
            field=models.CharField(default='octet-stream', max_length=50),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='type',
            field=models.CharField(default='application', max_length=20),
        ),
    ]
